### ISSUE TITLE
package compression

### ISSUE THREAD

**Issue by georgesterpu** [jonathonf/manjaro-nvidia#1]
Hi @jonathonf,

Thanks for making these very useful scripts, updating the video drivers was really easy.

Just wanted to point out that `sudo pacman -Udd *pkg*xz` did not work on my system.
`loading packages...
error: '*pkg*xz': could not find or read package`

Not an expert, but I guess that's because I've set `PKGEXT='.pkg.tar'` in `/etc/makepkg.conf` (have enough space and don't like waiting).

Regards,
George

**Comment by jonathonf** [comment]
If you change your system configuration from the defaults, then instructions based on the defaults won't work. ;) Hopefully anyone who _does_ change their settings will remember that's what they did.

I don't want to automate this any more than it already is as the idea was to introduce people to the package building process rather than giving a "one-click" installer; if I was going to do that I'd just build and upload the packages to a repo.
